### ISSUE TITLE
Implement all protocol defined methods

### ISSUE THREAD

**Issue by aBuder** [jicang/healywatch_reactive#26]
https://github.com/jicang/healywatch_reactive/blob/c329dfbd9c6679b9af11991cd5cd9a1d33d51836/healy_package/lib/healy_watch_sdk.dart#L33

https://github.com/jicang/healywatch_reactive/blob/c329dfbd9c6679b9af11991cd5cd9a1d33d51836/healy_package/lib/healy_watch_sdk.dart#L37

https://github.com/jicang/healywatch_reactive/blob/c329dfbd9c6679b9af11991cd5cd9a1d33d51836/healy_package/lib/healy_watch_sdk.dart#L46

https://github.com/jicang/healywatch_reactive/blob/c329dfbd9c6679b9af11991cd5cd9a1d33d51836/healy_package/lib/healy_watch_sdk.dart#L53

**Comment by jicang** [comment]
V1.6已经添加
