### ISSUE TITLE
Don't use late for vars.

### ISSUE THREAD

**Issue by aBuder** [jicang/healywatch_reactive#44]
We shouldn't use late for vars. 

https://github.com/jicang/healywatch_reactive/blob/abe622877efd3a513baf3c796339866b03b6b85a/healy_package/lib/healy_watch_sdk_impl.dart#L38

https://github.com/jicang/healywatch_reactive/blob/abe622877efd3a513baf3c796339866b03b6b85a/healy_package/lib/healy_watch_sdk_impl.dart#L109

https://github.com/jicang/healywatch_reactive/blob/abe622877efd3a513baf3c796339866b03b6b85a/healy_package/lib/util/bluetooth_conection_util.dart#L31

https://github.com/jicang/healywatch_reactive/blob/abe622877efd3a513baf3c796339866b03b6b85a/healy_package/lib/util/bluetooth_conection_util.dart#L34

https://github.com/jicang/healywatch_reactive/blob/abe622877efd3a513baf3c796339866b03b6b85a/healy_package/lib/util/bluetooth_conection_util.dart#L35

https://github.com/jicang/healywatch_reactive/blob/abe622877efd3a513baf3c796339866b03b6b85a/healy_package/lib/util/bluetooth_conection_util.dart#L41

https://github.com/jicang/healywatch_reactive/blob/abe622877efd3a513baf3c796339866b03b6b85a/healy_package/lib/util/bluetooth_conection_util.dart#L43

https://github.com/jicang/healywatch_reactive/blob/abe622877efd3a513baf3c796339866b03b6b85a/healy_package/lib/util/bluetooth_conection_util.dart#L50

https://github.com/jicang/healywatch_reactive/blob/abe622877efd3a513baf3c796339866b03b6b85a/healy_package/lib/util/bluetooth_conection_util.dart#L51

**Comment by jicang** [comment]
已修改
