### ISSUE TITLE
Cloud not start HealyWorkoutMode.breathing

### ISSUE THREAD

**Issue by aBuder** [jicang/healywatch_reactive#51]
We cloud not start the breathing workout.

If we call workout `startWorkout(HealyWorkoutMode.breathing)` no breathing workout is started

```
startWorkout(HealyWorkoutMode.breathing)
```

**Comment by jicang** [comment]
need call  startBreathingSession(
                HealyBreathingSession(
                    level,
                    durationInSeconds))

**Comment by aBuder** [comment]
I know that but in our old SDK it was possible to start breathing via this function

```
startWorkout(HealyWorkoutMode.breathing)
```

**Comment by ChrisMarxDev** [comment]
Still seems to be an issue.

**Comment by Danny23523** [comment]
The  startWorkout API in the old sdk without the level and durationsInSeconds(Now Training Times) parameters. If you still want to use the old API name, then sdk will give default value to the two parameters as before.
The default parameters will be same as the old sdk.

**Comment by ChrisMarxDev** [comment]
We will be using the alternative method, so that I can close this issue.

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl07.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22237773287624) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dS5MuHFY%2F%2FwNXpc8l%2BeCnSnMUYlVwn59rx29Jg%2F2sVA8ZeOWj5YDnzR82I7ZB5EXiA3sm2pA%2FijvgAw9aPMrrIMVHJwnfcgfcbjraV5JiSLFl0WJMUe%2FJwQLRF0XRDe%2B4I%3D>

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl07.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22237773287634) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dS5MuHFY%2F%2FwNXpc8l%2BeCnSn9gElKRJU1fFibrxop9gpB%2BP0%2FAR3n5GOBDM3%2FY6XbNtDaVuU4dIowXIpG%2BEjgi7HZIpmupwEaf42kFkrHQ5eyPNlHg58zbRvHa5GGxM%2FezA%3D>

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl02.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22238025021737) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dT5qKfgedu8YmKp5%2FBX%2BpCd76e7H6dbSYpZNe8o1AxgXKwoLP9oq%2BoEm4oUhB94Z%2Fw8RQwZ1xYK4Ol6n2Ji3djfPK8PuEOoZfCR0LI%2B6v2kZeq4Jx8ZoW5VqzZiZ9WOrbo%3D>

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl02.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22238025021733) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dT5qKfgedu8YmKp5%2FBX%2BpCdGvHBQAFDTzHjtTzrVML5UVBfE5DQ3zBKLBsrqUYE0%2FO%2BzDGjD4CyazhLT%2Bpn9wH62SvYqV8e6r19GuyER%2B7jZN8xqlFF5J6uvEThcIRqegY%3D>

**Comment by Danny23523** [comment]
Hello notifications，
 
Greetings! How have you been?
 
This is Molly from J-Style, one of the top ring professional manufacturer with own R&D Dep, all of the health management product are developed by own engineer, so we are able to provide any kind of the ODM or OEM service, even assembly the ring for you if you have your own design.
 
We are pleased to present you with the non-invasive glucose risk assessment smart ring, which is currently very popular in the market and is also the best-selling product in our company.
 
Please check details of our ring as below, if interested in, Welcome to send us your feedback, we will do our best to support.
 
J-Style Smart Ring key features and advantage of our rings (Model: 2301B):
 
• Pioneer in Glucose Risk Assessment: World's first smart ring with non-invasive glucose risk assessment.
 
• Sensorless Comprehensive Health Monitoring: 24/7 real-time monitoring of HR, SpO2, HRV, exercise, stress, body temperature, and blood glucose.
 
• Automatic Sleep Tracking: Monitors sleep stages (light/deep sleep, REM), sleep onset, and wake-up times.
 
• All-Day Activity Tracking: Includes pedometer, calorie consumption, distance, and daily goals.
 
• Women's Health Cycle Management: Covers menstruation and pregnancy.
 
• High-Precision Sensor and Patented Algorithm: Utilizes clinical-grade precision sensor and patented core algorithm.
 
• Lightweight and Stylish Design: Weighs approximately 3 grams, available in rose gold, space silver, and black.
 
• High-Performance and Low-Power Chip: Equipped with Nordic nRF52840 chip for high performance and ultra-low power consumption.
 
• Ultra-Long Battery Life and Fast Wireless Charging: 7 to 13 days battery life, less than 1-hour charging time, supports wireless charging.More better performance than Samsung Galaxy Ring.
 
• Supported OTA Upgrade: Provides wireless software update functionality.
 
• Outstanding Waterproof Performance: 5ATM level waterproof, suitable for various daily life occasions.
 
Welcome to try our samples, more new gens of rings will be launched this year, and I'll keep you updated.
 
If you have any questions or comments, feel free to leave a message. Thank you for your time.
 
Best Regards，
 

 



 

 
-----------------------------------
Molly Ou | Customer Manager
Mob/WeChat/WhatsApp/ Skype : +86-18877525911 
***@***.***
Joint Chinese Ltd. 

Web:http://email.prod.mailfamilyunited.com/c/eJxckE9v2zAMxT-NfItB0ZKVHnRo0hRrMGxds2xNL4X-JZZj2YZmx3U-_WBjC7AB5OER_D2Qz8ojGGE4T5ykApnAJaBICgmZoMYiKOsYGEpBaKMEOkeBIiBPvERABksUkIGAPBWaZwqWennHnM6dJgza2Ng0KF8dVfDV2Ne-czY1TUgqOQxDWja-7kwT23kWxsVFRUnEiiC-Lr6PrVs81ceGIJLsniBOTqe-fletf__fdVrC9Qyu-19dE1xcPNkbSrK1Lff9t_3j6k9vbHl_9_n8V3N1CHb7vOOTPhj4sdFnQ80VZubnpy-Ph7DdHej5xrzg9uv-9eXtecdLXRfd20Cyh6kY_PMXyTbTAeIhiTK6thoJrtTHcG6jFZe87K_-aPJw-nBVoywvo3AXXReFzdlVV4EwmKH05Lui13NQF4m_AwAA__-fjIrX(http://email.prod.mailfamilyunited.com/c/eJxckU1vozwQxz-NuQWZ8Rs5cGhe0NPo0W6aNNukl8rYJphgoA4kJZ9-BdrtYaWZkf7S_KSfZnSSYyUUY4FJIgFUQIxBBEUSUalEBDmmuRDAJCEGGM9ixSKhI4MDmwAGimMQmGCBeSgyRiSOs3hOTcZNhihufaNDJ22VS2eroa9tZ3SoGhdUSdF1LSJPCFIE6Y09it6G3siq9xUmoVII0s5LdUGQeqOtN6q7IpJe7blGZPV5376ZgSsuGhjU537HjltPKQIG6erl-Mr9_I6AO0RWwDFlsRgHiXDghtlN-gSJBQI4zl6H1sye67xBAJMOjL7nvv6Qrf34131cguUELvtr1zjjZ8_6G0VkqctD_3JIF396rcun-f-Xv5nJk9Ob7Z6N-aTwr3V2UZF64Il5--9HenKb_Sm6fDM72Pw8HHfv2z0rs7ro3u-IrMaiuGxs3anGt-NFEVmPAmIV-MSbthoQLOTX_dJ6LW687B82V9ydv0zVSM1KL8wtq4tCc_rIKoconqDwbLuiz6YX3RL4HQAA__-KL6gw) 

R&D Based: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**

**Comment by Danny23523** [comment]
Hello notifications，
 
Greetings! How have you been?
 
This is Molly from J-Style, one of the top ring professional manufacturer with own R&D Dep, all of the health management product are developed by own engineer, so we are able to provide any kind of the ODM or OEM service, even assembly the ring for you if you have your own design.
 
We are pleased to present you with the non-invasive glucose risk assessment smart ring, which is currently very popular in the market and is also the best-selling product in our company.
 
Please check details of our ring as below, if interested in, Welcome to send us your feedback, we will do our best to support.
 
J-Style Smart Ring key features and advantage of our rings (Model: 2301B):
 
• Pioneer in Glucose Risk Assessment: World's first smart ring with non-invasive glucose risk assessment.
 
• Sensorless Comprehensive Health Monitoring: 24/7 real-time monitoring of HR, SpO2, HRV, exercise, stress, body temperature, and blood glucose.
 
• Automatic Sleep Tracking: Monitors sleep stages (light/deep sleep, REM), sleep onset, and wake-up times.
 
• All-Day Activity Tracking: Includes pedometer, calorie consumption, distance, and daily goals.
 
• Women's Health Cycle Management: Covers menstruation and pregnancy.
 
• High-Precision Sensor and Patented Algorithm: Utilizes clinical-grade precision sensor and patented core algorithm.
 
• Lightweight and Stylish Design: Weighs approximately 3 grams, available in rose gold, space silver, and black.
 
• High-Performance and Low-Power Chip: Equipped with Nordic nRF52840 chip for high performance and ultra-low power consumption.
 
• Ultra-Long Battery Life and Fast Wireless Charging: 7 to 13 days battery life, less than 1-hour charging time, supports wireless charging.More better performance than Samsung Galaxy Ring.
 
• Supported OTA Upgrade: Provides wireless software update functionality.
 
• Outstanding Waterproof Performance: 5ATM level waterproof, suitable for various daily life occasions.
 
Welcome to try our samples, more new gens of rings will be launched this year, and I'll keep you updated.
 
If you have any questions or comments, feel free to leave a message. Thank you for your time.
 
Best Regards，
 

 



 

 
-----------------------------------
Molly Ou | Customer Manager
Mob/WeChat/WhatsApp/ Skype : +86-18877525911 
***@***.***
Joint Chinese Ltd. 

Web:http://email.prod.mailfamilyunited.com/c/eJxckE9vm0AQxT_NcgPtDrBrDnuIHaLGqtqkrtM4l2j_YRZYQGQxxZ--ArWWGmnm8Ebze5p5mhdYMZWmgeGEQcJgg-MsKDkFrSjdEGVIqjAxlNBUGjDMEMMoNYHlgCHBG2A4xoxkEVZgMkUESGCUUooS3A-djpywTSGcbeaxtd7oSHUuaPg0TVHV2darbujXmZvDixg4YlsE8Br-nHsTPrZFhwBQfIcAFqfz2L6L3r5_dl2WYLeCu_HDd84M4aO-oSje6eo4Ph8ftn8719Vd9rX-p1Nxcnr_dEgXfVL4JZe1IuqKV-bXl28PJ7c_vL3kN-YH7L8fX5_x0yGtZFv6twnF90sl-L-_UJwvB7D7YOCD6ZsZwVb8nup-OFe19x-e9VfrXOyhE7qVBTMX2ZalpslVNg4leIWis_XlKNegLhz-BAAA__-vk4r2(http://email.prod.mailfamilyunited.com/c/eJxckU1v4jwQxz-NcyNyxm_kkEN5iZ6iR7tQSgu9VI7tEEOcpMaBDZ9-FbTbw0ozI_2l-Uk_zeisxEooxiKTJQKogCkmaVRlbCq5odPSpLQEUZY6FSASSRmVSWJSGdkMMFA8BYEJFkkaYwUmVYmEAgTnnCOKO9_q2Elbl9LZeugbG4yOVeuiOqtC6BB5QpAjyK_sXvU29kbWva8xiZVCkAcv1RlB7o223qhwQSS_2GODyOLrtn43A1dctDCor-0L2689pQgY5IvN_pX79IaAO0QWwDFlUzEOQnHkhslV-gyJGQLYT16Hzkyem7JFAA8dGH2PffMpO_v5r_u4BPMHOO8voXXGT571N4rIXJ92_WaXz_70Up-e0v_PfzOTB6dX6y0b80Hht2VxVom64wfz_t-P_OBW24-35TfzAqufu_0Gr7fsVDRV-LghshiL4lNrm6Ba340XRWQ5CohF5DNvunpAMJO_bufOH0_nEC5BdHfrHAnQSt0UpTDXoqkqzem9qB2i-AHFRxuqvni86JrB7wAAAP__4QmocA) 

R&D Based: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**
