### ISSUE TITLE
The HealyOnlyPPGFinish object should also contain all collected PPG data

### ISSUE THREAD

**Issue by ChrisMarxDev** [jicang/healywatch_reactive#55]
Currently the `HealyOnlyPPGFinish` object returned from a ppg only measurement contains no data at all.
We need the object to return all collected  data like so: `List<HealyPPGData> ppgData`.
It should behave similar to the `HealyEcgSuccessData` data object, which also contains all ecg and ppg data of the measurement.

**Comment by ChrisMarxDev** [comment]
According to talks with the product owner, this particular ticket has lower priority.

**Comment by jicang** [comment]
不管是哪种ecg测量模式，ppg数据都是在HealyPPGData里面；OnlyPPG模式测量结束的时候是不会有其他数据返回的

**Comment by Danny23523** [comment]
Translation for above comment from engineer: No matter which ecg measurement mode is used, the ppg data is in HealyPPGData; when the measurement in OnlyPPG mode ends, no other data will be returned

**Comment by Danny23523** [comment]
PPG only include only the raw data of PPG, no other datas like ECG/HRV/Blood pressure, please confirm which data will you need include into, after confirmed the details, we need to fix from firmware.

**Comment by ChrisMarxDev** [comment]
We only need the PPG data on the PPG only measurement. No ECG or quality data is needed in the result element. It's just to make it fit our current data flow of measuring and processing the data.

**Comment by Danny23523** [comment]
PPG data include in the <HealyPPGData>, but no data returned to HealyOnlyPPGFinish.

**Comment by ChrisMarxDev** [comment]
That is exactly what this issue is about. We would like to receive the complete PPG Data in the  `HealyOnlyPPGFinish` object.

**Comment by Danny23523** [comment]
But it didn't return any data to HealyOnlyPPGFinish, but to HealyPPGData.

**Comment by Danny23523** [comment]
Also it is the raw data of PPG in HealyPPGData, please confirm what you need is raw PPG data or result of PPG? As we didn't give the result of PPG from this mode.

**Comment by ChrisMarxDev** [comment]
We expect the same raw data that is currently only sent in small chunks in the `HealyPPGData` event. It should just be collected as a complete list of all data inside of the `HealyOnlyPPGFinish`. This is not a big change. It just improves performance on our side since the watch sdk is already collecting these data points.

**Comment by Danny23523** [comment]
OK，will check with engineer and update.

**Comment by Danny23523** [comment]
Will update the SDK to meet your requirements.

**Comment by Danny23523** [comment]
Dear friends:This&nbsp;is&nbsp;Kitty&nbsp;from&nbsp;Joint&nbsp;Chinese&nbsp;Ltd&nbsp;,&nbsp;a&nbsp;manufacturer&nbsp;&amp;&nbsp;solution&nbsp;provider&nbsp;for&nbsp;digital&nbsp;health&nbsp;wearable.I&nbsp;am&nbsp;so&nbsp;glad&nbsp;to&nbsp;recommend&nbsp;our&nbsp;poplar&nbsp;product-&nbsp;2301B&nbsp;Smart Health&nbsp;Ring:Exclusive feature of J-Style:&nbsp;the world's first non-invasive glucose risk assessment smart ring.&nbsp;you can identify you are in prediabetes early and make timely life interventions, you may be able to delay the progression of prediabetes and even return to healthy blood glucose targets.More&nbsp;features SMART RING&nbsp;Health Management ***@***.*** Location:Factory address:Floor 1-3, Building 4, Building 6, Huafeng Technology Park, Guangtian Road, Luotian, Songgang, Bao'an Phone Number:Whatsapp/telephone: +86 15707683773www.jointcorp.com ....................................................................................... If you no longer wish to receive these emails, click on the following link: unsubscribe

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl07.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22237773287633) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dS5MuHFY%2F%2FwNXpc8l%2BeCnSnsaJrE%2FWuR6Kou4yHoEt499yysxAM%2Frl6lHMgPYB%2F2XQB9%2B7rlaYw18lnbT66HKz8cI3W2dO%2BS2hcZ8Agg9lEApT9FEjC3A0V0ze3P9kdj7Q%3D>

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl07.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22237773287623) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dS5MuHFY%2F%2FwNXpc8l%2BeCnSn4Po0Ke%2F7odLf7pMgmwXsmE%2B1m9ZLqI%2B6qxnhgZfctLrmvrwqi%2FSwyki8f7D1u3FYqfquTYeQnEOg57MndqW9zoHeK1jcLZDU9HkO47c1KKI%3D>

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl07.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22237773287631) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dS5MuHFY%2F%2FwNXpc8l%2BeCnSnqeXVGi3hmYWERSFTMWvT4cxGgrsLcL0hIHI9I04uZ9FZ8n6pbrA%2BWFfvDLnLhyLTl%2FwcSpODo8eieoleF1sTPlehKD9gQ2kiEysCtWnrHA4%3D>

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl02.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22238025021730) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dT5qKfgedu8YmKp5%2FBX%2BpCdzI3FDJx1tyHQ8okLeFebFmtGUVNrKZlNAXWHnsoS2KNB5aOkGOsKtFJdUHYuBiNZ3t%2BbtF2Y%2Bh3OJPA1L0%2FfdV9YQkbHCord8AXd1i2HWIU%3D>

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl02.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22238025021735) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dT5qKfgedu8YmKp5%2FBX%2BpCdoMquE2ug5pTTRgu2bj3b5Y5SSfHhl6%2B747akBeAg8RF8HhAkRNYx7vmosc0R%2B3%2FyTYELM2XiyJglqLoGyJyduPFLi%2F0npkpsom8ux3eqdaw%3D>

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl02.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22238025021739) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dT5qKfgedu8YmKp5%2FBX%2BpCdUPi2arGmDglAe72OuVD3bfds9V%2Bfkyli649fQyrWGZjKfHxt5EFAFoM6GABJSxJhBReUINbppk70vwevLohs6e2icTKAZDEvy9EKWMqMF3Y%3D>

**Comment by Danny23523** [comment]
Hello notifications，
 
Greetings! How have you been?
 
This is Molly from J-Style, one of the top ring professional manufacturer with own R&D Dep, all of the health management product are developed by own engineer, so we are able to provide any kind of the ODM or OEM service, even assembly the ring for you if you have your own design.
 
We are pleased to present you with the non-invasive glucose risk assessment smart ring, which is currently very popular in the market and is also the best-selling product in our company.
 
Please check details of our ring as below, if interested in, Welcome to send us your feedback, we will do our best to support.
 
J-Style Smart Ring key features and advantage of our rings (Model: 2301B):
 
• Pioneer in Glucose Risk Assessment: World's first smart ring with non-invasive glucose risk assessment.
 
• Sensorless Comprehensive Health Monitoring: 24/7 real-time monitoring of HR, SpO2, HRV, exercise, stress, body temperature, and blood glucose.
 
• Automatic Sleep Tracking: Monitors sleep stages (light/deep sleep, REM), sleep onset, and wake-up times.
 
• All-Day Activity Tracking: Includes pedometer, calorie consumption, distance, and daily goals.
 
• Women's Health Cycle Management: Covers menstruation and pregnancy.
 
• High-Precision Sensor and Patented Algorithm: Utilizes clinical-grade precision sensor and patented core algorithm.
 
• Lightweight and Stylish Design: Weighs approximately 3 grams, available in rose gold, space silver, and black.
 
• High-Performance and Low-Power Chip: Equipped with Nordic nRF52840 chip for high performance and ultra-low power consumption.
 
• Ultra-Long Battery Life and Fast Wireless Charging: 7 to 13 days battery life, less than 1-hour charging time, supports wireless charging.More better performance than Samsung Galaxy Ring.
 
• Supported OTA Upgrade: Provides wireless software update functionality.
 
• Outstanding Waterproof Performance: 5ATM level waterproof, suitable for various daily life occasions.
 
Welcome to try our samples, more new gens of rings will be launched this year, and I'll keep you updated.
 
If you have any questions or comments, feel free to leave a message. Thank you for your time.
 
Best Regards，
 

 



 

 
-----------------------------------
Molly Ou | Customer Manager
Mob/WeChat/WhatsApp/ Skype : +86-18877525911 
***@***.***
Joint Chinese Ltd. 

Web:http://email.prod.mailfamilyunited.com/c/eJxckE9v00AQxT_N-hZrM971OIc9NGkqGiEoCYGGS7V_43W8tmX8p-bTI1sQCaSZwxvN72nmGeGoRs15ZMUagSFkFDDKBTiOOnWbtXQUFbMctHSAG8e0U0Zi5AVQYDQDpAlFinGqsow7lbK1sQ7thjDatLWJg_Slk8GXU1_5zppY1yEqxTiOcVH7qtN12yyzMK0G2QqCWwLwuvo6NXb1XLmaAJDkgQDMTte-epONf_vfdV6C3QLu-p9dHWy7ejZ3lCQ7U5z7L-en7Z_em-Jh8_H2V3N5CebwcuKzvmj6ba9ueq1_0YX5_uHT0yUcThfI7swRDp_Pr8fjy4kXqsq7HyNJHudi9J-_SLKfD8DHqBWtbcqJwFa-j7emNaXXcnq3oSx0OjGdShPGAe2gqjy313IYMBBGFyi--i7v1RLUIOB3AAAA__9wo4xE(http://email.prod.mailfamilyunited.com/c/eJxckU1vm0AQhn_NcjNaZr_wgUNiGzVW1Tp23Ni9RMvuYtZmgaz5CPn1FajNodLMSK80j_RoRic5VkIxFpgkEkAFxBhEUCRZxCNGozxTgguhjSLcEEKWEeZLSnEU2AQwUByDwAQLLEKexTHLM04jbXJhlojixtc6dNKWuXS2HLvKtkaHqnZBmRRt2yDygCBFkPbss-hs6I0sO19iEiqFIG29VDcEqTfaeqPaOyLp3V4qRNbvw-7VjFxxUcOo3g97dtp5ShEwSNfPpxfulwMC7hBZA8eUxWIaJKKBGxe99AkSjwjgtHgZG7N4qvIaAcw6MPleuupNNvbtf_dpCVYzuOrube2MXzzpLxSRlb4eu-dj-vi3N_r6sPx--5eZPDu93R3YlM8K_9pkNxWpTzwzr99-pGe3PZwh_mL2sP15PO33uwO7ZlXR_h4QWU9F8bW2Vatq30wXRWQzCYh14BNvmnJE8Cg_hlvjdWmVHD-MK6-Kj1Rxqd3QC9NnVVGYS9n3wiGKZyi82LbosvlFfQJ_AgAA__8Akagj) 

R&D Based: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**

**Comment by Danny23523** [comment]
Hello notifications，
 
Greetings! How have you been?
 
This is Molly from J-Style, one of the top ring professional manufacturer with own R&D Dep, all of the health management product are developed by own engineer, so we are able to provide any kind of the ODM or OEM service, even assembly the ring for you if you have your own design.
 
We are pleased to present you with the non-invasive glucose risk assessment smart ring, which is currently very popular in the market and is also the best-selling product in our company.
 
Please check details of our ring as below, if interested in, Welcome to send us your feedback, we will do our best to support.
 
J-Style Smart Ring key features and advantage of our rings (Model: 2301B):
 
• Pioneer in Glucose Risk Assessment: World's first smart ring with non-invasive glucose risk assessment.
 
• Sensorless Comprehensive Health Monitoring: 24/7 real-time monitoring of HR, SpO2, HRV, exercise, stress, body temperature, and blood glucose.
 
• Automatic Sleep Tracking: Monitors sleep stages (light/deep sleep, REM), sleep onset, and wake-up times.
 
• All-Day Activity Tracking: Includes pedometer, calorie consumption, distance, and daily goals.
 
• Women's Health Cycle Management: Covers menstruation and pregnancy.
 
• High-Precision Sensor and Patented Algorithm: Utilizes clinical-grade precision sensor and patented core algorithm.
 
• Lightweight and Stylish Design: Weighs approximately 3 grams, available in rose gold, space silver, and black.
 
• High-Performance and Low-Power Chip: Equipped with Nordic nRF52840 chip for high performance and ultra-low power consumption.
 
• Ultra-Long Battery Life and Fast Wireless Charging: 7 to 13 days battery life, less than 1-hour charging time, supports wireless charging.More better performance than Samsung Galaxy Ring.
 
• Supported OTA Upgrade: Provides wireless software update functionality.
 
• Outstanding Waterproof Performance: 5ATM level waterproof, suitable for various daily life occasions.
 
Welcome to try our samples, more new gens of rings will be launched this year, and I'll keep you updated.
 
If you have any questions or comments, feel free to leave a message. Thank you for your time.
 
Best Regards，
 

 



 

 
-----------------------------------
Molly Ou | Customer Manager
Mob/WeChat/WhatsApp/ Skype : +86-18877525911 
***@***.***
Joint Chinese Ltd. 

Web:http://email.prod.mailfamilyunited.com/c/eJxckE9vm0AQxT_NcgMts8BuDnuIHUeNVbVJXdrYF2v_8X8BYWBLP30Fai010szhPc3vaWY0z7CiKo49w0MKEQWGCfEKnhiZaWykimiYKckSYERSpjPKVpd4JQcMEWZAMcE0hCBkRBLNNM5kbJR4QBHuh04HVpRNJmzZLFNbjkYHqrNew51zQdWV7ai6od88u_izGDiiOwTw7n9feuO_tFmHABB5RABrUj61V9GX14-p6xDsN3A_3cbOmsF_0XcUkb2u0uktfd797YOuHh8-1_90LM5WH19P8arPCv84yFqF6jfemJ-fvjyf7fF0Ses78w2OX9P3N_d6iivZFuPFIfK0VoT_uwuRw7oAffIGPpi-WRDsxC9X90MuiZv7gubdtLQuoYnQ0c0SM8u2KEzezDO1KMIbFOTlWExye9TM4U8AAAD__74ljFk(http://email.prod.mailfamilyunited.com/c/eJxckc9uozAQh5_G3ILM2MZw4NAmQdtotZs0zTbppTK2Aw4YqMOfpU-_Au32sNLMSD9pPunTjEquWHLJmKeTgAPlEGFCvCJhcYwBaMh0GEQ8iKKAMqxjLPk1DlQMnkkAA8URcEwwD8APIpIRFSl8zZiWIkYUt65RvhWmugprqqmvTaeVLxvrVUnRdS0iDwhSBOnAPove-E6LqncVJr6UCNLOCVkiSJ1WxmnZ3RFJ7yavEdl8jPtXPYUy5A1M8uP4zM57RykCBunmcH4JXTwiCC0iGwgxZRGfByGRZ6fVIFyC-CMCOK9eplavnuprgwAWHZh9875-F615_999XoL1Aq77e9dY7VZP6gtFZK1up_5wSh__9lbdHuLv5b_MxMWq3f7I5nyR-Nc2K2UgP_HCvH77kV7s7vh2Kr-YZ9j9PJ0P4_7IbllddG8jIpu5KL41pu5k49r5oohsZwG-8VzidFtNCB7F77FsXZ6RcWgLnjf9VI8hD4Wid0v0kNVFofNqGLhFFC-Qn5uu6LPlRUMCfwIAAP__W8Snxg) 

R&D Based: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**

**Comment by Danny23523** [comment]
Hello notifications，
 
Greetings! How have you been?
 
This is Molly from J-Style, one of the top ring professional manufacturer with own R&D Dep, all of the health management product are developed by own engineer, so we are able to provide any kind of the ODM or OEM service, even assembly the ring for you if you have your own design.
 
We are pleased to present you with the non-invasive glucose risk assessment smart ring, which is currently very popular in the market and is also the best-selling product in our company.
 
Please check details of our ring as below, if interested in, Welcome to send us your feedback, we will do our best to support.
 
J-Style Smart Ring key features and advantage of our rings (Model: 2301B):
 
• Pioneer in Glucose Risk Assessment: World's first smart ring with non-invasive glucose risk assessment.
 
• Sensorless Comprehensive Health Monitoring: 24/7 real-time monitoring of HR, SpO2, HRV, exercise, stress, body temperature, and blood glucose.
 
• Automatic Sleep Tracking: Monitors sleep stages (light/deep sleep, REM), sleep onset, and wake-up times.
 
• All-Day Activity Tracking: Includes pedometer, calorie consumption, distance, and daily goals.
 
• Women's Health Cycle Management: Covers menstruation and pregnancy.
 
• High-Precision Sensor and Patented Algorithm: Utilizes clinical-grade precision sensor and patented core algorithm.
 
• Lightweight and Stylish Design: Weighs approximately 3 grams, available in rose gold, space silver, and black.
 
• High-Performance and Low-Power Chip: Equipped with Nordic nRF52840 chip for high performance and ultra-low power consumption.
 
• Ultra-Long Battery Life and Fast Wireless Charging: 7 to 13 days battery life, less than 1-hour charging time, supports wireless charging.More better performance than Samsung Galaxy Ring.
 
• Supported OTA Upgrade: Provides wireless software update functionality.
 
• Outstanding Waterproof Performance: 5ATM level waterproof, suitable for various daily life occasions.
 
Welcome to try our samples, more new gens of rings will be launched this year, and I'll keep you updated.
 
If you have any questions or comments, feel free to leave a message. Thank you for your time.
 
Best Regards，
 

 



 

 
-----------------------------------
Molly Ou | Customer Manager
Mob/WeChat/WhatsApp/ Skype : +86-18877525911 
***@***.***
Joint Chinese Ltd. 

Web:http://email.prod.mailfamilyunited.com/c/eJxckFtvnDAQhX-NeVtkj_GaPvghu9moWfWSZrtt6EvkG2DAQFwupb--ArWRGmnm4YzmO5o5RuRYc81YZAXhkHBIMSVRKQzHe0LyHPYMc6OkThhPE5PL1FhDtI6cAAwJToFjijkhsaZcacoB1N4qDIAS3IfOxF66JpfeNcvYusGaWHc-asQ8z3HVuXbQXei3mV92kwwC8QMCeNp9XXq7u2_zDgEgeoMAVqdibJ9l757fuq5LcNzA4_hz6LwNu3vziiJ6NNV1_HK9O_ztk6lu3n2o_2kmM2_ODxe26kzjbydVa6J_4435_v7TXebPl8x_fGUe4fz5-vQYHi6sUm05_JgRvV0rwf_9hehpPYDfRkEE2zcLgoP8Ndd9UOBnv7zsXVNzurw0hTRMt4OdVFuWtmimiXuU4A2KCzeUo9qCmgT8CQAA___D34v_(http://email.prod.mailfamilyunited.com/c/eJxckU2P2jAQhn-NcyOajOMYDjksH1EX9YOFpQu9rBzbEEOcBOOEZn99lajdQ6WZkV5pHunRjEpPILlkLNBpxDHmOAUaBUU6U-KEVAKTFPgUME4Uy2EGVEwl0EgEJkXAGKbIgQKPolBSnkvKEfNE54BIYmhcrUIrTHkS1pR9WxmvVShrG5Rp4X1D6BPBjGDWsY-iNaHTomxdCTSUkmDmnZBXgpnTyjgt_Z3Q7G7OFaHL22PzpvtEJrzGXt52W3bYuDgmyDBbvhxeEzd7EEwsoUtMIGZTPgycscD2k064lPA5QTxMXvtGT56rU00QRx0cfM9t9S4a8_6_-7CEixFctHdfW-0mz-oTJXShLvv2ZZ_N__ZKXZ5mX6__MhNHq9abHRvyUcLPVX6VkfyAkXn78j072vXuaL99Mltc_9gftm6zY5e8KvyvB6HLoWK41KbysnbNcFFCV4MAXwYudbope4Jz8ftxbVyO9mH7W2LKK6f9rTwLxWTldZdXRaHPZddxS2IYofBsfNHm44u6FP8EAAD__yZ7qGs) 

R&D Based: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**
