### ISSUE TITLE
startWorkout throws Exceptions for some HealyWorkoutMode 

### ISSUE THREAD

**Issue by ChrisMarxDev** [jicang/healywatch_reactive#56]
The `  Stream<HealyBaseExerciseData> startWorkout(HealyWorkoutMode workoutMode)` function does not properly start a workout for the following types: `dancing, basketball, hiking, fitness` and instead throws a `HealyEnterExerciseFailed` exception.

This also leads to the whole connection failing and not being recoverable until the device is unpaired and paired again.

**Comment by jicang** [comment]
开启运动模式只能开启指定的几种运动模式，通过`setWorkOutType(List<int> list)`设置

**Comment by ChrisMarxDev** [comment]
Followup: How do we correctly set the WorkOutType? The Function only takes in a List of int, but when we use the index of a workout item it does not seem to work for properly.
E.g. 
```setSelectedWorkoutType(HealyWorkoutType[
         HealyWorkoutMode.cycling.index,
          HealyWorkoutMode.dancing.index,
          HealyWorkoutMode.hiking.index,
          HealyWorkoutMode.fitness.index,
])
``` 
(Index: 1,7,9,10)

This results in only the indexes `[1,7,9]` being returned from `getAllWorkoutTypes()`.
The watch itself only shows `Cycling, Basketball, Gym` as types. This is completely wrong.

When I then start a workout with the type `HealyWorkoutModel.hiking.index` throws an error.

**Comment by jicang** [comment]
因为breath模式不能在这里面设置，所以breath模式之后的index都要-1

**Comment by ChrisMarxDev** [comment]
That seems like very unsafe design and it is not documented anywhere. Please improve the code or write some documentation to avoid having this issue in the future.

**Comment by Danny23523** [comment]
Will update the SDK next Monday

**Comment by Danny23523** [comment]
SDK updated on github,please check

**Comment by ChrisMarxDev** [comment]
Works great, I will close this issue.

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl07.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22237773287625) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dS5MuHFY%2F%2FwNXpc8l%2BeCnSnVQbgtaXg6HikK36Dk7lOu5o2G%2BSAHjoe8puao1DfyGlwgyroGPnLYuc6edHEYchZR%2BnBd29r8oJfHsf9VAaX7w2j98WCUrPb8KchYZhc2VU%3D>

**Comment by Danny23523** [comment]
Hi notifications,


 


It's Leo from J-Style again, how are you doing?
 
The core product we would like to introduce is our smart health rings, as you may know,
nowadays many big brands has launched or planning to launch their rings, such as Apple, Samsung, OPPO, Amazfit, etc.
We believe there is a big market for the smart rings this year in the smart wearable filed.
 

Below some brief information of our rings (model 2301B) for your reference:

 * Non-invasive blood glucose risk assessment monitor 
 * Automatic / manual heart rate & SpO2 monitor 
 * Automatic HRV & stress level monitor (auto measurement time interval can be set via APP) 
 * Automatic sleep tracking (light/deep sleep, REM, awake, on/off bed time, sleep HR/SpO2/HRV, sleep efficiency, etc) 
 * Member's Health (tracking the health of your group members in real time after joining a health group no matter how far away) 
 * All day activity tracking (steps/calories/distance/activity time/daily goal achievement) 
 * VO2max fitness tracking 
 * Temperature trends monitoring 
 * Women's menstrual cycle & pregnancy period management 
 * 15-day memory saved, easy to check daily/weekly/monthly data report on App 
 * Wireless charging, battery supports about 7-10 days with default setting of auto health vitals monitoring per day 
 * Wear detection 
 * Low battery reminder (APP) 
 * Automatic firmware updates (OTA) via "JCRing" App 
 * Firmware customization and SDK/API supported 
 * OEM / ODM customization supported Besides, we are proud to announce that we are the world's first manufacturer of a non-invasive diabetes risk assessment ring and have conducted a clinical study at KK Women's and Children's Hospital in Singapore.
 
Feel free to contact me for more details :)
 
 

Best regards
 
Leo Lee | Customer Manager| Tel:+86 15521509424
Joint Chinese Ltd. 

Web:www.jointcorp.com(http://v5zhui.realurl02.cc/track/redirects?sign=7e8ONUNdyhzVfXjLC%2FGt0jfpVFex%2FxJv&m=22238025021728) 

R&D Base: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**




If you no longer wish to receive these emails, click on the following link:https://getter.autobegan16.com/unsubscribe?t=KgLUfWf18dT5qKfgedu8YmKp5%2FBX%2BpCdZT%2F50pELihaDYfsVT5TMqyMgzP5IB447Wq7aoql5Z%2Bli3ftP61RLl76P69DStiMl%2BbTMxihuHO8B2eFnJZtcpY0PVfHZQ3QQm7HTSx4fbUQ%3D>

**Comment by Danny23523** [comment]
Hello notifications，
 
Greetings! How have you been?
 
This is Molly from J-Style, one of the top ring professional manufacturer with own R&D Dep, all of the health management product are developed by own engineer, so we are able to provide any kind of the ODM or OEM service, even assembly the ring for you if you have your own design.
 
We are pleased to present you with the non-invasive glucose risk assessment smart ring, which is currently very popular in the market and is also the best-selling product in our company.
 
Please check details of our ring as below, if interested in, Welcome to send us your feedback, we will do our best to support.
 
J-Style Smart Ring key features and advantage of our rings (Model: 2301B):
 
• Pioneer in Glucose Risk Assessment: World's first smart ring with non-invasive glucose risk assessment.
 
• Sensorless Comprehensive Health Monitoring: 24/7 real-time monitoring of HR, SpO2, HRV, exercise, stress, body temperature, and blood glucose.
 
• Automatic Sleep Tracking: Monitors sleep stages (light/deep sleep, REM), sleep onset, and wake-up times.
 
• All-Day Activity Tracking: Includes pedometer, calorie consumption, distance, and daily goals.
 
• Women's Health Cycle Management: Covers menstruation and pregnancy.
 
• High-Precision Sensor and Patented Algorithm: Utilizes clinical-grade precision sensor and patented core algorithm.
 
• Lightweight and Stylish Design: Weighs approximately 3 grams, available in rose gold, space silver, and black.
 
• High-Performance and Low-Power Chip: Equipped with Nordic nRF52840 chip for high performance and ultra-low power consumption.
 
• Ultra-Long Battery Life and Fast Wireless Charging: 7 to 13 days battery life, less than 1-hour charging time, supports wireless charging.More better performance than Samsung Galaxy Ring.
 
• Supported OTA Upgrade: Provides wireless software update functionality.
 
• Outstanding Waterproof Performance: 5ATM level waterproof, suitable for various daily life occasions.
 
Welcome to try our samples, more new gens of rings will be launched this year, and I'll keep you updated.
 
If you have any questions or comments, feel free to leave a message. Thank you for your time.
 
Best Regards，
 

 



 

 
-----------------------------------
Molly Ou | Customer Manager
Mob/WeChat/WhatsApp/ Skype : +86-18877525911 
***@***.***
Joint Chinese Ltd. 

Web:http://email.prod.mailfamilyunited.com/c/eJxckE-PmzAQxT-NuYHMYGM4-LDJZtWNqna7adrQS2RsEyCALYc_IZ--AvWPWmnm8Ebze5p5ihdYMkmpp3nIgDBIMCReyYUOSZ6mAuIwplKqJCxypbEkkYRYM-VVHDAQnADDEWaYBamKCSYhYKp0QRgggq0zKmhF1RSirZp56Kpeq0Ca1mv4NE1Bbaqul8bZddbO_igcR2yDAE7-19lq_7UrDAJA0RMCWJwuQ3cWtjr_77oswXYFt8OtN612_qv6g6Joq-rj8OX4svnVO1U_pR-vvzUVWav2bwe66Ezib7v8KkP5wCvz_cOnl6zdH7LHX-Yd9p-Pp_f67UDrvCv7HxOKnpci-J-_ULRbDmDPnuNO22ZGsBH36Wqduo2GyDsMlN2nggojFC2t1WPelaW-uM71AyJ4hYJL1ZdDvgY1cvgZAAD__1sHi7o(http://email.prod.mailfamilyunited.com/c/eJxckU2PmzAQhn-NuQU5YxvDgcNuEtSNqjabbLpJLytjm2DC1zoGQn59BeqHVGlmpFeaR3o0o-IMSy4Z83S85EA5hBhCL4_DMMRMAI8gUiEQQYKIK4FJkNIs5SnzTAwYKA6BY4I55n6kAorpEjBTOqMcEMWtbZRfCVNmojLl2NXGaeXLpvLKOHeuReQJQYIg6dkj74xvtSg7W2LiS4kgcVbIK4LEamWslu6GSHIzlxqR9eewe9djIAPewCg_D3t22llKETBI1q-nt8BGA4KgQmQNAaYs5NMgS-5V46IXNkb8GQGcFm9jqxcvddYggFkHJt9LV3-I1nz87z4twWoGV93NNZW2ixf1F0VkpYpj93pMnn_3RhVP0dfrn8zEuVLb3YFN-Szxj016lUv5wDPz_uVbcq62h_PjH7OH7ffjaV_sDqxI69z9HBBZT0Vx0Zjayca200UR2UwCfO3Z2Oq2HBE8i_twba269Q2Vd-gYvw8ZE41QLG9b3ad1nuuLra3rEMUz5F-My7t0flEfw68AAAD__3msqBo) 

R&D Based: Building 40-2, Zhongjizhigu Tech Park, Nanshan Road， Songshanhu, Dongguan, Guangdong, P.R China
Factory Add: Building 4 & 6, Huafeng Tech Park, Guangtian Road, Luotian Industrial Area, Songgang Town, Bao’an District, Shenzhen, P.R China



**Factory Qualification: ISO13485,ISO14000,ISO9001,FDA,BSCI,Target, Walmart factory auditing**
