### ISSUE TITLE
Replace `print` usages with `log` or other alternatives

### ISSUE THREAD

**Issue by BradKwon** [jicang/healywatch_reactive#82]
I noticed that there are `print` usages here and there and this is critical in terms of security. Please replace all `print` with `log` or other alternatives. I am going to create a new bug issue for that. And this guideline would be useful for you.

https://www.kindacode.com/snippet/flutter-avoid-print-calls-in-production-code/

**Comment by badjio** [comment]
**Update:** Please also replace remaining `print` usages in these files as well:
    - `/healywatch_reactive/healy_package/lib/ble/ble_device_connector.dart`
    - `/healywatch_reactive/healy_package/lib/ble/ble_device_interactor.dart`

**Comment by badjio** [comment]
Fixed by using `debugPrint`. But this solution is not optimal, since `debugPrint` is only a wrapper around `print`.
Better solution for future is to use `log` or add a check for environment (`kReleaseMode`/`kDebugMode`) and only print when it's on debug mode.
